name: genGraphIET
dependencies:
  - python
  - numpy
  - pandas
  - gunicorn
  - chardet
  - pip
  - pip:
    - dash 
    - dash-bootstrap-components
    - dash-daq
    - plotly
    - kaleido
    - chart-studio
    
