name: genGraphIET
dependencies:
  - python
  - numpy
  - pandas
  - gunicorn
  - chardet
  - repro-zipfile
  - pip
  - pip:
    - dash 
    - dash-bootstrap-components
    - dash-daq
    - plotly
    - kaleido==0.2.1
    - chart_studio
    - openpyxl
    
